### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by WilliamWangPeng** [he426100/OpenArkCompiler#2]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119221749-56d54900-bb23-11eb-8356-f453a7fc95da.png)

thank you  
best regards to you  
William

**Comment by he426100** [comment]
https://gitee.com/openarkcompiler/OpenArkCompiler
